name: neixtest
services:
  nginx:
    image: nginx:1.27-alpine
    container_name: neix-nginx
    ports:
      - "8088:80"
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/app:ro
    depends_on:
      - php
    networks:
      - neixnet

  php:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: neix-php
    volumes:
      - ./app:/var/www/app
      - ./public:/var/www/public
      - ./composer.json:/var/www/composer.json:ro
      - ./vendor:/var/www/vendor
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
      - DB_HOST=db
      - DB_NAME=neix
      - DB_USER=root
      - DB_PASS=root
    depends_on:
      - db
    networks:
      - neixnet

  ws:
    build:
      context: .
      dockerfile: docker/ws/Dockerfile
    container_name: neix-ws
    ports:
      - "8080:8080"
    volumes:
      - ./app:/var/www/app
      - ./composer.json:/var/www/composer.json:ro
      - ./vendor:/var/www/vendor
    depends_on:
      - db
    networks:
      - neixnet

  db:
    image: mariadb:11
    container_name: neix-db
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=neix
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - neixnet

  adminer:
    image: adminer:4
    container_name: neix-adminer
    ports:
      - "8081:8080"
    networks:
      - neixnet

volumes:
  dbdata:

networks:
  neixnet:
    driver: bridge
